nervosnetwork/muta-devops

watchdog/index.js

provides:
- /get-node [node-name]
- /get-node-list [tag]
- /help

Add a cli interface for tg bot 

---

k8s/fluentd-elasticsearch/README.md
k8s/fluentd-elasticsearch/diff.txt
k8s/fluentd-elasticsearch/es-persistent-volume.yaml
k8s/fluentd-elasticsearch/es-service.yaml
k8s/fluentd-elasticsearch/es-statefulset.yaml
k8s/fluentd-elasticsearch/fluentd-es-configmap.yaml
k8s/fluentd-elasticsearch/fluentd-es-ds.yaml
k8s/fluentd-elasticsearch/kibana-deployment.yaml
k8s/fluentd-elasticsearch/kibana-service.yaml

Add some necessary config files to show how to start es/kibana on k8s.
- Data is stored in persistent volume now

Add fluentd-elasticsearch

---

k8s/es-crontab-clean/Dockerfile
k8s/es-crontab-clean/build.sh
k8s/es-crontab-clean/go.mod
k8s/es-crontab-clean/kube.yaml
k8s/es-crontab-clean/main.go

```sh
$ ./es-crontab-clean -es http://127.0.0.1:9200 -n 7
```
means delete data older than 7 days.

Auto clean elasticsearch's data

---

ecs/.gitignore
ecs/README.md
ecs/requirements.txt
ecs/res/config.toml
ecs/res/db/security_group_dict.json
ecs/res/db_bench/instance_list.json
ecs/res/db_bench/security_group_dict.json
ecs/res/secret_template.toml
ecs/src/acdb.py
ecs/src/build.py
ecs/src/conf.py
ecs/src/deploy.py
ecs/src/ecs.py
ecs/src/main.py
ecs/src/main_fuzz.py
ecs/src/monitor/.gitignore
ecs/src/monitor/index.js
ecs/src/monitor/package-lock.json
ecs/src/monitor/package.json
ecs/src/oam.py
ecs/src/util.py

See the [README.md](https://github.com/nervosnetwork/muta-devops/compare/master...mohanson:update?expand=1#diff-5a07327bc96bf00ab3c9e206b9bf8dbb)

feat(ecs): Auto request aliyun ECS by configs

---

watchdog/index.js
watchdog/kube.yaml

fix: variable bugs

---

muta-bot/env/dev.json
muta-bot/env/prod.json
muta-bot/kube-template.yaml
muta-bot/package.json
muta-bot/src/auto_k8stest.ts
muta-bot/src/config.ts
muta-bot/src/db.ts
muta-bot/src/index.ts
muta-bot/src/push.ts
muta-bot/src/weekly.ts
watchdog/index.js

- watch pull request and auto start a chaos test on k8s cluster
- an entry point that can start a test manually

feat: watch pr and auto test

---

muta-bot/.gitignore
muta-bot/env/dev.json
muta-bot/env/prod.json
muta-bot/package.json
muta-bot/src/config.ts
muta-bot/src/daily.ts
muta-bot/src/db.ts
muta-bot/src/index.ts
muta-bot/src/notification.ts
muta-bot/src/weekly.ts

1.add delay label to delay task
2.remind reviewers everyday
3.create daily report issue and sendMessage to telegram group
4.fix code check
5.delay issue statistics in daily report

delay label,remind reviewers,create daily report issue

---

muta-bot/env/dev.json
muta-bot/env/prod.json
muta-bot/src/config.ts
muta-bot/src/daily.ts
muta-bot/src/notification.ts

- 1. add 'daily issue this week' in daily report
- 2. add weekly_meeting_url_friday

some feature

---

muta-bot/src/auto_k8stest.ts

The sample reportor is:
https://github.com/nervosnetwork/muta/pull/217#issuecomment-619505424
The output of the benchmark currently taken directly.

Add performance test report to issue comment.

---

muta-bot/kube-template.yaml
muta-bot/src/auto_k8stest.ts

- Test lasts 2 hours now
- chaos: open all

change options for auto test

---

k8s/muta-operator/pkg/controller/muta/muta_controller.go
muta-bot/kube-template.yaml

Did not go to mount persistant volume before.

fix persistant volume

---

apm/README.md
apm/monitor/config/grafana/grafana.ini
apm/monitor/config/grafana/provisioning/notifiers/notifiers.yaml
apm/monitor/docker-compose.yml

support initial configuration of alerting.

feat: support alert function

---

grafana/muta-node v2.json

feat: dashboard-upgrade

---

apm/README.md
apm/docs/metrics.md

 docs: add metrics description

---

apm/README.md
apm/docs/metrics.md

Resolving the Legacy of [#55](https://github.com/nervosnetwork/muta-devops/pull/55)

docs: update metrics.md

---

apm/README.md
apm/docs/alert_table.md

Add a list of alerts for easy subsequent maintenance and viewing

docs: Add alert list document

---

apm/docs/alert_table.md

Give the alert level an initial value for easy discussion and modification.

docs: alert level

---

apm/monitor/docker-compose.yml

fix: clock skew adjustments

---

apm/agent/docker-compose.yml
apm/docs/docker-compose.md
apm/docs/metrics.md
apm/monitor/config/grafana/dashboards/muta-node.json
apm/monitor/config/promethues/prometheus.yml
grafana/muta-node.json

feat: Add component monitoring

---

apm/docs/alert_table.md
apm/monitor/config/grafana/dashboards/muta-benchmark.json
apm/monitor/config/grafana/dashboards/muta-node.json
grafana/muta-benchmark.json
grafana/muta-node.json

feat: Update dashboard v4

---

apm/docs/metrics.md
apm/monitor/config/grafana/dashboards/muta-benchmark.json
apm/monitor/config/grafana/dashboards/muta-network.json
apm/monitor/config/grafana/dashboards/muta-node.json
apm/monitor/config/promethues/muta-network-rules.yml
apm/monitor/config/promethues/prometheus.yml
grafana/muta-benchmark.json
grafana/muta-network.json
grafana/muta-node.json

feat: muta network dashboard 
